from pathlib import Path
p=Path('lib/core/widgets/blocks.dart');s=p.read_text(encoding='utf-8');s=s.replace("import 'package:flutter/material.dart';", "import 'package:flutter/material.dart';\nimport 'skin_style.dart';");start=s.index('    var color =');end=s.index('    if (invalid)',start);s=s[:start]+'''    final style = SkinStyle.of(skin);
    var color = value == 0 ? style.empty : style.colors[(value - 1).clamp(0, 4)];
'''+s[end:];s=s.replace('color: const Color(0x55eefaff),','color: SkinStyle.of(skin).base,');p.write_text(s,encoding='utf-8')
p=Path('lib/core/widgets/game_ui.dart');s=p.read_text(encoding='utf-8').replace("import '../services/storage_status.dart';", "import '../services/storage_status.dart';\nimport 'skin_style.dart';");s=s.replace("                Image.asset(\n                  'assets/backgrounds/coast.png',", "                if (p.selectedSkin != 'default')\n                  SkinBackdrop(skin: p.selectedSkin),\n                if (p.selectedSkin == 'default') Image.asset(\n                  'assets/backgrounds/coast.png',");p.write_text(s,encoding='utf-8')
p=Path('lib/features/gameplay/presentation/game_screen.dart');s=p.read_text(encoding='utf-8').replace("import '../../../core/widgets/game_ui.dart';", "import '../../../core/widgets/game_ui.dart';\nimport '../../../core/widgets/skin_style.dart';");s=s.replace("? tr(ref, 'Muhteşem!', 'Incredible!')", "? 'Awesome!'").replace("? tr(ref, 'Mükemmel!', 'Perfect!')", "? 'Excellent!'").replace(": tr(ref, 'Harika!', 'Great!');", ": 'Great!';");p.write_text(s,encoding='utf-8')
p=Path('lib/features/gameplay/presentation/game_layout.dart');s=p.read_text(encoding='utf-8');start=s.index('        body: DecoratedBox(');end=s.index('          child: SafeArea(',start);s=s[:start]+'''        body: SkinBackdrop(
          skin: p.selectedSkin,
'''+s[end:];p.write_text(s,encoding='utf-8')
p=Path('lib/features/gameplay/presentation/board_view.dart');s=p.read_text(encoding='utf-8').replace("import '../../../core/widgets/blocks.dart';", "import '../../../core/widgets/blocks.dart';\nimport '../../../core/widgets/skin_style.dart';").replace('color: const Color(0xff182d51),','color: SkinStyle.of(widget.skin).base,').replace('Border.all(color: const Color(0xff5878a5), width: 2)', 'Border.all(color: SkinStyle.of(widget.skin).colors.first.withValues(alpha: .6), width: 2)');p.write_text(s,encoding='utf-8')
p=Path('lib/features/shop/shop_screen.dart');s=p.read_text(encoding='utf-8').replace("import '../../core/widgets/blocks.dart';", "import '../../core/widgets/blocks.dart';\nimport '../../core/widgets/skin_style.dart';");s=s.replace("'Candy', 790", "'Candy', 250").replace("'Ocean', 990", "'Ocean', 300").replace("'Sunset', 4990", "'Sunset', 400").replace("'Forest', 4990", "'Forest', 500").replace("'Night', 8990", "'Night', 700");s=s.replace('builder: (context, bounds) => ListView(', 'builder: (context, bounds) => FitPage(').replace('Center(child: DecorativeBoard(skin: item.$1))', '''ClipRRect(
                          borderRadius: BorderRadius.circular(12),
                          child: SkinBackdrop(skin: item.$1,
                            child: Center(child: Padding(padding: const EdgeInsets.all(8), child: DecorativeBoard(skin: item.$1)))),
                        )''');s=s.replace("'Bloklar', 'Blocks'", "'Renk Paketleri', 'Color Packs'");s=s.replace("'Yalnızca oyun içinde kazanılan altın kullanılır. Gerçek para ile satın alma yoktur.'", "'Her paket: özel arka plan, tahta ve blok renkleri. Kalıcı açılır; yalnızca oyun altını.'").replace("'Only coins earned in the game are used. There are no real-money purchases.'", "'Every pack includes a background, board and block palette. Unlock forever with game coins.'");p.write_text(s,encoding='utf-8')
